# Generated by Django 2.0.6 on 2018-06-12 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 2, 49, 45, 820227, tzinfo=utc)),
        ),
    ]
