# Generated by Django 2.0.6 on 2018-06-12 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180612_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 3, 15, 21, 143023, tzinfo=utc)),
        ),
    ]
